ProyectoDistribuidora/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoDistribuidora.Data;
using ProyectoDistribuidora.Models;
/*Librerias para la autentificación de formularios*/
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;

namespace ProyectoDistribuidora.Controllers
{
    public class LoginController : Controller
    {
        /*Variable para manejar todas las variables del contexto*/
        private ProyectoDistribuidoraContext context;

        /// <summary>
        /// Contructor con Parametors
        /// </summary>
        /// <param name="cnt">Context</param>
        public LoginController(ProyectoDistribuidoraContext cnt)
        {
            this.context = cnt;
        }

        /// <summary>
        /// Muestra la vista de una lista con todos los usuarios registrados
        /// </summary>El administrador y gerente solo podrá ver esta lista
        /// <returns>Retorna la lista de Usuarios en una tabla</returns>
        [HttpGet]
        public async Task<IActionResult> ListaUsuarios()
        {
            return View(await context.Usuarios.ToListAsync());
        }


        /// <summary>
        /// Retorna la vista del index, este Index contiene los componentes Form, para loguear
        /// </summary>
        /// <returns>Index</returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }// 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([Bind] Usuarios user)
        {
            try
            {
                var temp = this.ValidarUsuarios(user);
                /*Se pregunta si el usuario se validó correctamente*/
                if (temp != null)
                {
                    var userClaims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name,temp.Email),
                        new Claim(ClaimTypes.Name,temp.Email),
                        new Claim(ClaimTypes.Email, temp.Email),
                        new Claim(ClaimTypes.Role,temp.IdRol.ToString()),
                    };

                    var grandmaIdentity = new ClaimsIdentity(userClaims, "User Identity");

                    var userPrincipal = new ClaimsPrincipal(new[] { grandmaIdentity });

                    HttpContext.SignInAsync(userPrincipal);

                    return RedirectToAction("Index","Home");
                }

                TempData["mensaje"] = "Error usuario o contraseña incorrecta";
                return View(user);
            }
            catch (Exception)
            {

                throw;
            }
        }

        /// <summary>
        /// Retorna la vista para que el usuario puede crear su cuenta.
        /// </summary>Este método Get se utiliza en 2 ocasiones, el Adinisstrador puede crear un usuario o el mismo usuario puede llenar sus datos
        /// <returns>Vista CrearCuenta</returns>
        [HttpGet]
        public IActionResult CrearCuenta()
        {
            return View();
        }//

        /// <summary>
        /// Método post para cargar los datos del usuario a la base de datos
        /// </summary>
        /// <param name="usuario"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CrearCuenta([Bind] Usuarios usuario)
        {
            try
            {
                /*Primero se necesita validar si el modelo es valido*/
                if (ModelState.IsValid)
                {
                    /*Si fuera valido el id rol siempre será 3 cuando se hace por logueo,genera la contraseña*/
                    usuario.IdRol = 3;
                    usuario.FechaIngreso = DateTime.Now;
                    usuario.Contrasena = this.generarClave();
                    /*Agregar el objeto*/
                    this.context.Usuarios.Add(usuario);
                    /*Guardar cambio*/
                    this.context.SaveChanges();
                    /**/
                    Email email = new Email();
                    /*Generando el cuerpo de los datos del email*/
                    string html = "Bienvenidos a la Distribuidora UCR gracias por ser parte de nuestra plataforma web";
                    html += "<br A continuación detallamos los datos registrados en nuestra plataforma web>";
                    html += "<br> <b>Cédula: </b> " + usuario.Cedula;
                    html += "<br> <b>Tipo Cédula: </b> " + usuario.TipoCedula;
                    html += "<br> <b>Nombre Completo: </b> " + usuario.NombreCompleto;
                    html += "<br> <b>Teléfono: </b> " + usuario.Telefono;
                    html += "<br> <b>Dirección: </b> " + usuario.Direccion;
                    html += "<br> <b>Email: </b>" + usuario.Email;
                    html += "<br> <b>Contraseña: </b>" + usuario.Contrasena;
                    /*Datos que se envian al método enviar de la clase Email*/
                    email.enviar(usuario.Email, @"wwwroot/css/imagenes/FirmaDistribuidora.jpg",html, "Bienvenidos a la Distribuidora UCR gracias por ser parte de nuestra plataforma web");
                   /*Mensaje que se muestra en la parte superior del form , informando que todo salió correctamente*/
                    TempData["mensaje"] = "Usuario creado correctamente. Sú contraseña se envió al correo";
                    /*Si todo sale correcto , redirecciona a Crear Cuenta*/
                    return RedirectToAction("CrearCuenta");
                }
                else
                {
                    /*Mensaje que se muestra en la parte superior del form , informando que todo salió correctamente*/
                    TempData["mensaje"] = "No se registró correctamente";
                    return View(usuario);
                }

            }
            catch (Exception ex)
            {
                TempData["mensaje"] = "Error.2" + ex.Message;
                return View(usuario);
            }
         
            
        }//Fin metodo crear Cuenta

        /// <summary>
        /// Método que genera una clave de forma al azar
        /// </summary>
        /// <returns>Contrasañe</returns>
        private string generarClave()
        {
            try
            {
                Random random = new Random();
                string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789";
                return new string(Enumerable.Repeat(chars, 12).Select(s => s[random.Next(s.Length)]).ToArray());
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

         /*     
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarios = await context.Usuarios
                .FirstOrDefaultAsync(m => m.Cedula == id);
            if (usuarios == null)
            {
                return NotFound();
            }

            return View(usuarios);
        }
        */

        /// <summary>
        /// Para editar los datos del usuario
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarios = await context.Usuarios.FindAsync(id);
            if (usuarios == null)
            {
                return NotFound();
            }
            return View(usuarios);
        }

        // POST: Login/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Cedula,TipoCedula,NombreCompleto,Telefono,Direccion,Email,FechaIngreso,Contrasena,IdRol")] Usuarios usuarios)
        {
            if (id != usuarios.Cedula)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    context.Update(usuarios);
                    await context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuariosExists(usuarios.Cedula))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ListaUsuarios));
            }
            return View(usuarios);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarios = await context.Usuarios
                .FirstOrDefaultAsync(m => m.Cedula == id);
            if (usuarios == null)
            {
                return NotFound();
            }

            return View(usuarios);
        }

        // POST: Login/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var usuarios = await context.Usuarios.FindAsync(id);
            context.Usuarios.Remove(usuarios);
            await context.SaveChangesAsync();
            return RedirectToAction(nameof(ListaUsuarios));
        }

        private bool UsuariosExists(string id)
        {
            return context.Usuarios.Any(e => e.Cedula == id);
        }

        /// <summary>

ProyectoDistribuidora/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoDistribuidora.Data;
using ProyectoDistribuidora.Models;

namespace ProyectoDistribuidora.Controllers
{
    public class ProductosController : Controller
    {
        private readonly ProyectoDistribuidoraContext _context;

        public ProductosController(ProyectoDistribuidoraContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }// 

        // GET: Productos
        public async Task<IActionResult> ListaProductos()
        {
            return View(await _context.Productos.ToListAsync());
        }

        // GET: Productos/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productos = await _context.Productos
                .FirstOrDefaultAsync(m => m.CodigoBarra == id);
            if (productos == null)
            {
                return NotFound();
            }

            return View(productos);
        }

        // GET: Productos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Productos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(List<IFormFile> files, [Bind("CodigoBarra,Tipo,Descripcion,PrecioCompra,ImpuestoValor,Exento,PrecioTotalProducto,UnidadMedida,Estado,Foto,Fecha,IdProveedor")] Productos productos)
        {
            if (ModelState.IsValid)
            {
                string rutaFisica = AppDomain.CurrentDomain.BaseDirectory;
                string filePath = rutaFisica.Substring(0, rutaFisica.Length - 24);
                filePath += @"wwwroot\css\imagenes\";
                string fileName = "";

                foreach (var formFile in files)
                {
                    if (formFile.Length > 0)
                    {
                        fileName = productos.CodigoBarra + "-" + formFile.FileName;
                        fileName = fileName.Replace(" ", "_");
                        filePath += fileName;

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await formFile.CopyToAsync(stream);
                            productos.Foto = "/css/imagenes/" + fileName;
                        }//fin del using
                    }//fin del if formFile
                }//fin del foreach

                _context.Add(productos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }//fin del if modelstate
            return View(productos);
        }//fin del método create

        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productos = await _context.Productos.FindAsync(id);
            if (productos == null)
            {
                return NotFound();
            }
            return View(productos);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CodigoBarra,Tipo,Descripcion,PrecioCompra,ImpuestoValor,Exento,PrecioTotalProducto,UnidadMedida,Estado,Foto,Fecha,IdProveedor")] Productos productos)
        {
            if (id != productos.CodigoBarra)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductosExists(productos.CodigoBarra))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(productos);
        }

        // GET: Productos/Delete/
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productos = await _context.Productos
                .FirstOrDefaultAsync(m => m.CodigoBarra == id);
            if (productos == null)
            {
                return NotFound();
            }

            return View(productos);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var productos = await _context.Productos.FindAsync(id);
            _context.Productos.Remove(productos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductosExists(string id)
        {
            return _context.Productos.Any(e => e.CodigoBarra == id);
        }
    }
}

ProyectoDistribuidora/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoDistribuidora</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @*Menu opciones*@
    <header class="img-fluid" id="imagenback">

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom mb-3">
            <div class="container-fluid" style="padding:60px">
                <div>
                    @*Boton del menun*@
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="nav navbar-nav flex-grow-1">
                        @*Items del menú de opciones*@
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="" asp-action="">Inicio</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Productos" asp-action="Create">Productos</a>
                        </li>

                        @if (User.Identity.IsAuthenticated && User.IsInRole("1"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">Proveedores</a>
                                @*Sumbmenu opciones para agregar o ver lista de Usuarios*@
                                <div class="dropdown-menu">
                                    <a class="dropdown-item nav-link " asp-controller="Proveedores" asp-action="CrearProveedor">Crear Proveedor</a>
                                    <a class="dropdown-item nav-link" asp-controller="Proveedores" asp-action="ListaProveedores">Lista Proveedores</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">Productos</a>
                                @*Sumbmenu opciones para agregar o ver lista de Productos*@
                                <div class="dropdown-menu">
                                    <a class="dropdown-item nav-link " asp-controller="" asp-action="">Crear Producto</a>
                                    <a class="dropdown-item nav-link" asp-controller="Productos" asp-action="ListaProductos">Lista Productos</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">Usuarios</a>
                                @*Sumbmenu opciones para agregar o ver lista de Usuarios*@
                                <div class="dropdown-menu">
                                    <a class="dropdown-item nav-link " asp-controller="Login" asp-action="CrearCuenta">Crear Usuario</a>
                                    <a class="dropdown-item nav-link" asp-controller="Login" asp-action="ListaUsuarios">Lista Usuarios</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="" asp-action="">Bitácora</a>
                            </li>
                            <li class="nav-item dropdown ml-auto">
                                @*Sumbmenu opciones para Sesion de Inicio Ya el usuario está autentificado*@
                                <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">@User.Identity.Name</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item nav-link  " asp-controller="Login" asp-action=""> Cambiar Contraseña</a>
                                    <a class="dropdown-item nav-link " asp-controller="Login" asp-action="Logout">Cerrar Sesión</a>
                                </div>
                            </li>
                        }
                        else
                        {

                            @if (User.Identity.IsAuthenticated && User.IsInRole("2"))
                            {
                                @*Lista Ventas, solo el gerente puede ver esta opción*@
                                <li class="nav-item">
                                    <a class="nav-link " asp-area="" asp-controller="" asp-action="">Lista Ventas</a>
                                </li>
<<<<<<< HEAD
                            }
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item dropdown ml-auto">
                                    @*Sumbmenu opciones para Sesion de Inicio Ya el usuario está autentificado*@
                                    <a class="nav-link dropdown-toggle  ml-auto" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">@User.Identity.Name</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item nav-link text-black-50 " asp-controller="Login" asp-action=""> Cambiar Contraseña</a>

                                        <a class="dropdown-item nav-link text-black-50" asp-controller="Login" asp-action="Logout">Logout</a>

                                        <a class="dropdown-item nav-link text-black-50" asp-controller="Login" asp-action="Logout">Cerrar secion</a>

                                    </div>
                                </li>
                            }
                            else
                            {
                                @*Sumbmenu opciones para Sesion de Inicio y no está autentificado todavía*@
                                <li class="nav-item dropdown ml-auto">
                                    <a class="nav-link dropdown-toggle  ml-auto" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">Tú Cuenta</a>

                                    <div class="dropdown-menu">
                                        <a class="dropdown-item nav-link text-black-50 " asp-controller="Login" asp-action="Index">Iniciar Sesión</a>
                                        <a class="dropdown-item nav-link text-black-50" asp-controller="Login" asp-action="CrearCuenta">Registrarse</a>
                                    </div>
                                </li>
                            }

                        }
=======

                                @*Carrito*@
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="" asp-action="">Carrito</a>
                                </li>
                                <li class="nav-item dropdown ml-auto">
                                    @*Sumbmenu opciones para Sesion de Inicio Ya el usuario está autentificado*@
                                    <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">@User.Identity.Name</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item nav-link  " asp-controller="Login" asp-action=""> Cambiar Contraseña</a>
                                        <a class="dropdown-item nav-link " asp-controller="Login" asp-action="Logout">Cerrar Sesión</a>
                                    </div>
                                </li>
                            }
                            else
                            {

                                @if (User.Identity.IsAuthenticated)
                                {
                                    @*Carrito*@
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="" asp-action="">Carrito</a>
                                    </li>
                                    <li class="nav-item dropdown ml-auto">
                                        @*Sumbmenu opciones para Sesion de Inicio Ya el usuario está autentificado*@
                                        <a class="nav-link dropdown-toggle  ml-auto" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">@User.Identity.Name</a>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item nav-link text-black-50 " asp-controller="Login" asp-action=""> Cambiar Contraseña</a>

                                            <a class="dropdown-item nav-link text-black-50" asp-controller="Login" asp-action="Logout">Cerrar Sesión</a>

                                        </div>
                                    </li>

                                }
                                else
                                {
                                    @*Sumbmenu opciones para Sesion de Inicio y no está autentificado todavía*@
                                    <li class="nav-item dropdown ml-auto">
                                        <a class="nav-link dropdown-toggle  ml-auto" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">Tú Cuenta</a>

                                        <div class="dropdown-menu">
                                            <a class="dropdown-item nav-link text-black-50 " asp-controller="Login" asp-action="Index">Iniciar Sesión</a>
                                            <a class="dropdown-item nav-link text-black-50" asp-controller="Login" asp-action="CrearCuenta">Registrarse</a>
                                        </div>
                                    </li>
                                }@*Fin del if para Cliente*@
                            }@*Fin del if para Gerente*@

                        }@*Fin del if para Administrador*@
>>>>>>> 4292ca251bc64c7aa9f4ea0d1b33deb65670710c
                    </ul>
                </div> 
            </div>
        </nav>
    </header>
    <div id="box_lista">

        @RenderBody()

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ProyectoDistribuidora - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>